services:
  app:
    build: .
    container_name: node_app
    ports:
      - "8020:8020"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=concesionariodb
      - DB_PORT=3306
      - JWT_SECRET=token123
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "sleep 10 && npm run migrate && npm run seed && npm start"

  db:
    image: mysql:8
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: concesionariodb
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data: